"""empty message

Revision ID: 4fa2c9220817
Revises: a5945a4be94d
Create Date: 2022-09-16 20:05:57.139714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa2c9220817'
down_revision = 'a5945a4be94d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_loged_in', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_loged_in')
    # ### end Alembic commands ###
