"""empty message

Revision ID: f7f73ef6609e
Revises: 4fa2c9220817
Create Date: 2022-09-16 20:13:44.356206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f73ef6609e'
down_revision = '4fa2c9220817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_logged_in', sa.Text(), nullable=True))
    op.drop_column('user', 'last_loged_in')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_loged_in', sa.TEXT(), nullable=True))
    op.drop_column('user', 'last_logged_in')
    # ### end Alembic commands ###
